apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  selector:
    app: product-service
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: product-service
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 1
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: swadharma/product-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PROFILES
          value: kubernetes
        - name: PORT
          value: "8082"
        - name: DBURL
          valueFrom:
            secretKeyRef:
              name: database
              key: dburl
        - name: DBUSERNAME
          valueFrom:
            secretKeyRef:
              name: database
              key: dbusername
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: dbpassword
        ports:
        - containerPort: 8082
