server:
  port: ${PORT:8082}
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: product-service
  profiles:
    active: ${PROFILES}
  datasource:
    url: ${DBURL:jdbc:postgresql://20.187.149.117:5432/bukatoko}
    username: ${DBUSERNAME:postgres}
    password: ${DBPASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    kubernetes:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework: debug
    hibernate:
      type:
        descriptor:
          sql: trace
